from flask import Flask, render_template, request, jsonify
import requests
import os
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# Dynamic quiz questions generated by DOBBY
QUIZ_QUESTIONS = []

@app.route('/')
def quiz():
    return render_template('simple_quiz.html')

@app.route('/api/generate-quiz', methods=['POST'])
def generate_quiz():
    """Generate 10 fresh questions from DOBBY"""
    try:
        api_key = os.getenv('FIREWORKS_API_KEY')
        model = os.getenv('DOBBY_MODEL', 'accounts/fireworks/models/llama-v3p1-8b-instruct')
        
        prompt = """You are DOBBY, an upbeat blockchain tutor. Generate exactly 10 multiple-choice blockchain questions. Each question should be different and cover various blockchain topics like DeFi, NFTs, consensus, smart contracts, etc.

Format your response as a JSON array with this exact structure:
[
  {
    "question": "Question text here?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correct": 0
  }
]

Make sure:
- Each question is unique and educational
- Options are realistic and challenging
- Correct answer index (0-3) is accurate
- Cover different blockchain topics
- Keep questions clear and concise

Return ONLY the JSON array, nothing else."""
        
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.8,
            "max_tokens": 2000
        }
        
        response = requests.post(
            "https://api.fireworks.ai/inference/v1/chat/completions",
            headers=headers,
            json=payload
        )
        
        if response.status_code == 200:
            result = response.json()
            dobby_response = result["choices"][0]["message"]["content"]
            
            # Try to parse JSON from DOBBY's response
            import json
            try:
                # Clean up response if it has extra text
                start = dobby_response.find('[')
                end = dobby_response.rfind(']') + 1
                if start != -1 and end != 0:
                    json_str = dobby_response[start:end]
                    questions = json.loads(json_str)
                    
                    # Validate questions
                    if len(questions) == 10:
                        global QUIZ_QUESTIONS
                        QUIZ_QUESTIONS = questions
                        return jsonify({"success": True, "questions": questions})
                    else:
                        return jsonify({"error": f"Expected 10 questions, got {len(questions)}"})
                else:
                    return jsonify({"error": "Could not find JSON in response"})
            except json.JSONDecodeError as e:
                return jsonify({"error": f"Invalid JSON from DOBBY: {str(e)}"})
        else:
            error_detail = ""
            try:
                error_response = response.json()
                error_detail = f" - {error_response.get('error', {}).get('message', 'Unknown error')}"
            except:
                error_detail = f" - {response.text[:200]}"
            return jsonify({"error": f"API error: {response.status_code}{error_detail}"})
            
    except Exception as e:
        return jsonify({"error": str(e)})

@app.route('/api/questions')
def get_questions():
    """Get current quiz questions"""
    return jsonify(QUIZ_QUESTIONS)

@app.route('/api/quiz-summary', methods=['POST'])
def quiz_summary():
    """Get DOBBY's summary and feedback after quiz completion"""
    try:
        data = request.json
        score = data.get('score', 0)
        total = data.get('total', len(QUIZ_QUESTIONS))
        percentage = round((score / total) * 100) if total > 0 else 0
        
        api_key = os.getenv('FIREWORKS_API_KEY')
        model = os.getenv('DOBBY_MODEL', 'accounts/fireworks/models/llama-v3p1-8b-instruct')
        
        prompt = f"""You are DOBBY, an upbeat blockchain tutor. A student just completed your blockchain quiz and scored {score}/{total} ({percentage}%).

Give them personalized feedback about their performance. Be encouraging, mention specific areas they did well in or could improve on, and suggest next learning steps. Keep it motivational and under 150 words.

Don't just repeat their score - give meaningful insights about their blockchain knowledge journey."""

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.8,
            "max_tokens": 300
        }
        
        response = requests.post(
            "https://api.fireworks.ai/inference/v1/chat/completions",
            headers=headers,
            json=payload
        )
        
        if response.status_code == 200:
            result = response.json()
            dobby_response = result["choices"][0]["message"]["content"]
            return jsonify({"response": dobby_response})
        else:
            return jsonify({"response": f"Excellent work completing the quiz! You scored {score}/{total}. Every question you answered correctly shows your growing blockchain expertise. Keep exploring this fascinating technology! 🚀"})
            
    except Exception as e:
        return jsonify({"response": f"Congratulations on completing the blockchain quiz! You scored {score}/{total}. Each question you tackled brings you closer to mastering blockchain technology. Keep learning and stay curious! 🤖"})

if __name__ == '__main__':
    print("🎓 Starting Dobby the Educator...")
    print("📡 Each quiz will have 10 fresh questions generated by Dobby the Educator!")
    app.run(debug=True, port=5001)
